
services:
  postgres:
    image: postgres:15
    container_name: todo-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: perntodo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    image: todo-backend
    container_name: todo-backend
    depends_on:
      - postgres
    env_file:
      - ./server/.env.docker
    ports:
      - "5000:5000"

  frontend:
    image: todo-frontend
    container_name: todo-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgres_data:
