apiVersion: v1
kind: Service
metadata:
  name: todo-postgres
  namespace: todo-app
spec:
  clusterIP: None
  selector:
    app: todo-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432